name: Sync Fork

on:
  schedule:
    - cron: '0 10 * * 0'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.TOKEN }}
          owner: briankavanaugh
          base: master
          head: master
